openapi: 3.0.0
info:
  title: Custom GPT Knowledge Base API
  description: API to upload files to a custom GPT's knowledge base.
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Local API server for testing

paths:
  /upload:
    post:
      summary: Upload a file to the knowledge base
      operationId: uploadFile
      x-openai-isConsequential: true
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File successfully uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Bad request (e.g., no file part or no file selected)

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY

security:
  - ApiKeyAuth: []
